### PR TITLE
use lowercase names for MSVCP100.DLL / MSVCR100.DLL

### PR DESCRIPTION
**Pull request by hefloryd**
This fixes a problem where the DLL:s were not being extracted from the bundle.

### CODE REVIEW

**Comment by hefloryd** [comment]
This should fix #1. Tested on a clean Windows 10 with a 32-bit JVM. Without this fix MSVCP100.DLL and MSVCR100.DLL are missing from the list of extracted DLL:s.

**Comment by markphip** [comment]
Why is this a problem now?  I committed those files about 10 years ago and they have never been changed since.

**Comment by hefloryd** [comment]
I couldn't find exactly what triggers extraction of the DLL:s but presumably somewhere the process is now case-sensitive?

**Comment by markphip** [comment]
Possibly.  I used to produce all builds manually from a Windows system but now they are automated via Travis CI.  So maybe with jobs running on Linux now the files were not getting included.  I have triggered jobs to update the 1.9.7 packages on the update site.  If you want to verify that the fixed version is published we can close the issue.

Of course anyone that already has these DLL's on their system path would also not notice the problem making it harder to notice.

Thanks!

**Comment by hefloryd** [comment]
I just installed into a clean Windows 10 Eclipse (64-bit JVM this time) without issues. I now see the msvc dll:s in the configuration/org.eclipse.osgi folder, along with the other subversion dll:s, where they were missing previously. Looks good to me!

**Pull request merged**
